import {
  IsString,
  IsOptional,
  IsUUID,
  IsBoolean,
  IsUrl,
  IsDate,
} from 'class-validator';

export class CreateProductImageDto {
  @IsUUID()
  @IsOptional() // optional as the id is auto-generated by the database
  id: string;

  @IsUUID()
  product_id: string;

  @IsUUID()
  @IsOptional()
  variant_id: string;

  @IsString()
  image_url: string;

  @IsBoolean()
  is_main: boolean;

  @IsDate()
  @IsOptional() // Optional as it may be set on creation, but not required
  created_at: Date;

  @IsDate()
  @IsOptional() // Optional for when the image is updated
  updated_at: Date;
}
